#!/usr/bin/env bash
# see https://docs.docker.com/compose/completion/
mkdir -p ~/.zsh/completion
curl -L https://raw.githubusercontent.com/docker/compose/$(docker-compose version --short)/contrib/completion/zsh/_docker-compose > ~/.zsh/completion/_docker-compose

echo "fpath=(~/.zsh/completion $fpath)" >> ~/.zshrc

autoload -Uz compinit && compinit -i
exec $SHELL -l
