execute pathogen#infect()

syntax on

set number              " Show line numbers
set cursorline          " highlight current line
set showmatch           " set show matching parenthesis
set autoindent

syntax on
set background=dark
let g:solarized_termtrans = 1  "MacOS (iTerm)
colorscheme hybrid
