execute pathogen#infect()

syntax on

filetype on
filetype plugin on
filetype indent on

set encoding=utf8

" airline
let g:airline_powerline_fonts = 1

" Color scheme
set background=dark
let g:solarized_termtrans = 1  " MacOS (iTerm)
colorscheme hybrid

set relativenumber      " relative line number (usefull for dd command!)
set number              " Show line numbers
set cursorline          " highlight current line
set showmatch           " set show matching parenthesis
set autoindent          " autoindent
set copyindent          " copy the previous indentation on autoindenting
set ignorecase          " set case insensitivity
set mouse=a             " enable mouse

set listchars=tab:⇥·,trail:~,extends:>,precedes:<,space:.
set list

" NERDTree (type :NERDTree)
" NERDTree automatically when vim starts up if no files were specified
autocmd StdinReadPre * let s:std_in=1
autocmd VimEnter * if argc() == 0 && !exists("s:std_in") | NERDTree | endif



" GitGutter
let g:gitgutter_sign_column_always = 1
" see: https://github.com/airblade/vim-gitgutter#faq
highlight SignColumn        ctermbg=235
highlight GitGutterAdd      guifg=#009900 guibg=NONE ctermfg=2 ctermbg=235
highlight GitGutterChange   guifg=#bbbb00 guibg=NONE ctermfg=3 ctermbg=235
highlight GitGutterDelete   guifg=#ff2222 guibg=NONE ctermfg=1 ctermbg=235

" Highlight words to avoid in tech writing
" ========================================
"
"   http://css-tricks.com/words-avoid-educational-writing/
"   https://github.com/pengwynn/dotfiles/blob/12159ea233180344be4e25d57056ccd37061a153/vim/vimrc.symlink
"
highlight TechWordsToAvoid ctermbg=red ctermfg=white
match TechWordsToAvoid /\cobviously\|basically\|simply\|of course\|clearly\|just\|everyone knows\|however,\|so,\|easy\|assuming\|intuitively\|however/
autocmd BufWinEnter * match TechWordsToAvoid /\cobviously\|basically\|simply\|of course\|clearly\|just\|everyone knows\|however,\|so,\|easy\|assuming\|intuitively\|however/
autocmd InsertEnter * match TechWordsToAvoid /\cobviously\|basically\|simply\|of course\|clearly\|just\|everyone knows\|however,\|so,\|easy\|assuming\|intuitively\|however/
autocmd InsertLeave * match TechWordsToAvoid /\cobviously\|basically\|simply\|of course\|clearly\|just\|everyone knows\|however,\|so,\|easy\|assuming\|intuitively\|however/
autocmd BufWinLeave * call clearmatches():q:
