code --install-extension abusaidm.html-snippets
code --install-extension alefragnani.project-manager
code --install-extension christian-kohler.npm-intellisense
code --install-extension christian-kohler.path-intellisense
code --install-extension cssho.vscode-svgviewer
code --install-extension dbaeumer.vscode-eslint
code --install-extension donjayamanne.githistory
code --install-extension eamodio.gitlens
code --install-extension EditorConfig.EditorConfig
code --install-extension Equinusocio.vsc-community-material-theme
code --install-extension Equinusocio.vsc-material-theme
code --install-extension equinusocio.vsc-material-theme-icons
code --install-extension esbenp.prettier-vscode
code --install-extension GitHub.vscode-pull-request-github
code --install-extension HookyQR.beautify
code --install-extension hoovercj.vscode-power-mode
code --install-extension jpoissonnier.vscode-styled-components
code --install-extension ms-azuretools.vscode-docker
code --install-extension ms-vsliveshare.vsliveshare
code --install-extension msjsdiag.debugger-for-chrome
code --install-extension octref.vetur
code --install-extension Orta.vscode-jest
code --install-extension PKief.material-icon-theme
code --install-extension pnp.polacode
code --install-extension rust-lang.rust
code --install-extension silvenon.mdx
code --install-extension stylelint.vscode-stylelint
code --install-extension VisualStudioExptTeam.vscodeintellicode
code --install-extension vscode-icons-team.vscode-icons
code --install-extension waderyan.gitblame
code --install-extension WallabyJs.quokka-vscode
code --install-extension whizkydee.material-palenight-theme
code --install-extension wix.vscode-import-cost
code --install-extension znck.grammarly
